version: '3'
services:
  app_port:
    build: PortfolioBack
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://ua33z2phovw09hht:FfCNEofYQUh4yyPArBR2@bt6xqfblyx0rqx9oxjwj-mysql.services.clever-cloud.com:3306/bt6xqfblyx0rqx9oxjwj?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: ua33z2phovw09hht
      DB_PASSWORD: FfCNEofYQUh4yyPArBR2
    restart: always
    depends_on:
      ua33z2phovw09hht:
          condition: service_healthy
  ua33z2phovw09hht:
    image: mysql:8.0.28
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: FfCNEofYQUh4yyPArBR2
      MYSQL_DATABASE: ua33z2phovw09hht
    restart: always
    healthcheck:
      test: ["CMD", mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
